image: ubuntu1804

build: off
  
init:
- sh: sudo apt -yq update > /dev/null
- sh: sudo apt install -yq --no-install-suggests --no-install-recommends build-essential gcc-8 g++8 automake libtool-bin libgtest-dev libarmadillo-dev > /dev/null
- sh: git clone -b develop https://bitbucket.hdfgroup.org/scm/hdffv/hdf5.git
- sh: ls -al 

install:
- sh: ps -ef

test_script:
- sh: echo Howdy! 
